name: Build DocFX and Deploy to gh-page

on:
  push:
    branches:
      - main  # main 브랜치에서 푸시 이벤트 발생 시 실행
    paths:
      - "DocFX/**"  #  src/DocFX/** 폴더 내 변경 사항이 있을 경우에만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. .NET 설치
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # DocFX에 필요한 .NET 버전

      # 3. DocFX 설치
      - name: Install DocFX
        run: dotnet tool install -g docfx

      # 4. DocFX 빌드 실행
      - name: Build DocFX
        run: docfx build DocFX/docfx.json

      # 5. 빌드 결과를 main 브랜치의 /docs 디렉토리에 복사하고 푸시
      - name: Deploy to /docs in main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 기본 GitHub 제공 토큰
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          rm -rf ./docs
          mkdir -p ./docs
          cp -r DocFX/_site/* ./docs/
          git add ./docs
          git commit -m "Deploy DocFX site to /docs [skip ci]" || echo "No changes to commit"
          git push origin main
